### ISSUE TITLE
Nitro emote bypass does not work. (Streaming does though!)

### ISSUE THREAD

**Issue by Mr-Foxtrot** [oSumAtrIX/BetterDiscordPlugins#1]
Basically the emote will show up for a second in the message, only to be removed and turned back into the normal text for the emote name. Reactions are the same.

The stream quality bypass works flawlessly though. Good job on that!

![GIF](https://i.imgur.com/3KvFxfV.gif)

**Comment by oSumAtrIX** [comment]
Issue only in PC, PC not supported as of now.
