### ISSUE TITLE
Better Discord can't compile NitroEmoteAndScreenShareBypass.plugin.js

### ISSUE THREAD

**Issue by N3w0nee** [oSumAtrIX/BetterDiscordPlugins#12]
**Describe the bug**
Unable to compile the file

**To Reproduce**
Add NitroEmoteAndScreenShareBypass.plugin.js to the plugin folder

**Screenshots/ Videos**
![image](https://user-images.githubusercontent.com/35236187/142442541-92979f9f-7135-4a3f-a2d6-cab978810033.png)

**Comment by IPX21** [comment]
Yeah same can you fix this please

**Comment by oSumAtrIX** [comment]
I have tried using the plugin on a clean installation of discord and betterdiscord. The plugin has worked fine.
Which version of the plugin do you use and which version of bd/ed?

**Comment by N3w0nee** [comment]
Bd 1.3.0, just tried repairing and tried redownloading the plugin again to no avail. Just to take things out of the table, ¿Is it just saving link as and then getting the .js file, right?

**Comment by N3w0nee** [comment]
Okey @IPX21 and I made the same error, saving link doesn't work, it downloads a js, but not related to the actual script so I just copied and pasted it inside the file, it worked. ¿Is there a more obvious way to download the file?

**Comment by oSumAtrIX** [comment]
You need to open the raw view and then right-click to save the plugin:
![Raw view](https://user-images.githubusercontent.com/13122796/142746826-5d4a68c6-2bc1-4b4d-8bf8-559d9fc14e9e.png)
