### ISSUE TITLE
Auto-update feature

### ISSUE THREAD

**Issue by skelly37** [oSumAtrIX/BetterDiscordPlugins#13]
Would you mind adding some kind of auto-update script? I'd be really useful not to track the repo status and simply let the BetterDiscord handle all the stuff. Plus there's lots of installers to be simply copypasted and modified only slightly :)

To be more specific, it should look like that:
https://github.com/rauenzi/BetterDiscordAddons/blob/master/Plugins/PermissionsViewer/PermissionsViewer.plugin.js

**Comment by skelly37** [comment]
From what I can see you can simply link the raw text as well but I don't know exactly it's handled: https://mwittrien.github.io/BetterDiscordAddons/Plugins/ChatAliases/ChatAliases.plugin.js

I'm no js/Discord plugins expert, it's up to you HOW and IF it's going to be handled, though I'm ready to help.

**Comment by Corwin616** [comment]
bump
