### ISSUE TITLE
Smileys can't load correct

### ISSUE THREAD

**Issue by Geromo94** [oSumAtrIX/BetterDiscordPlugins#15]
![image](https://user-images.githubusercontent.com/37875880/148682614-310f5cd8-b47c-4d78-a79d-40062d202ec0.png)

![image](https://user-images.githubusercontent.com/37875880/148682649-87cfaf11-7ba1-4efc-83b7-53aa78e791fd.png)

**Comment by oSumAtrIX** [comment]
Thanks. Fixed with commit bfa1eeda223ad70614162a2408e40c1faedf2b62.
