### ISSUE TITLE
Emote sending broken after new update

### ISSUE THREAD

**Issue by SpookieGames** [oSumAtrIX/BetterDiscordPlugins#16]
It seems like new discord update broke the emote function. Hope you can fix it soon!

**Comment by oSumAtrIX** [comment]
Please attach error logs

**Comment by SpookieGames** [comment]
How do I find the error log?

**Comment by oSumAtrIX** [comment]
You need to check the electron developer console. I tried the plugin and it works for me.

**Comment by SpookieGames** [comment]
I mean it works when you click the emoji in the emoji selection but when you type it like :heh: it doesn't work. It just sends the :heh: as a message. Is it supposed to do that?

**Comment by SpookieGames** [comment]
https://user-images.githubusercontent.com/41782443/150682939-759fe59d-b84b-4b20-b8f7-0c8a579f94b6.mp4

**Comment by oSumAtrIX** [comment]
Yeah it is supposed to do that, check the [about](https://github.com/oSumAtrIX/BetterDiscordPlugins#-about) section.
