### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by Serega007RU** [oSumAtrIX/BetterDiscordPlugins#17]
**Describe the bug**
Spamming an error in the console

**To Reproduce**
Launch discord (after launch, this error will be in the console)
Navigating through guilds or channels will also spam this error in the console

**BD/ ED Version**
BetterDiscord 1.3.0

**Screenshots/ Videos**
![image](https://user-images.githubusercontent.com/64780091/150686105-7ebf1c11-8256-402e-aa91-f3f6b17f099b.png)

**Additional context**
![image](https://user-images.githubusercontent.com/64780091/150686206-22b5c4a7-7e72-4062-8858-219feaa0beba.png)

**Comment by oSumAtrIX** [comment]
This does not happen with my discord instance. Can you copy that line into the console (without the last ' )

**Comment by Serega007RU** [comment]
I didn't understand what exactly I should write in the console? This?
![image](https://user-images.githubusercontent.com/64780091/150931839-6f25c58c-b4e9-4cbc-b9f1-3d03ad9b50c4.png)

**Comment by Serega007RU** [comment]
It looks like this error appears when you switch to the friends tab, and there really are no buttons there.

**Comment by oSumAtrIX** [comment]
Fixed in latest commit
