### ISSUE TITLE
Emotes are not working on v3.6.4

### ISSUE THREAD

**Issue by TioIlluminati** [oSumAtrIX/BetterDiscordPlugins#19]
I installed NitroEmoteAndScreenShareBypass plugin but the emotes are not working. Hope you can fix it.

**Comment by oSumAtrIX** [comment]
Please follow the issue template:
![image](https://user-images.githubusercontent.com/13122796/150880482-16c3f9db-e14a-4f96-b85c-2f85fef13ef2.png)
