### ISSUE TITLE
Auto-update doesn't work as intended 

### ISSUE THREAD

**Issue by skelly37** [oSumAtrIX/BetterDiscordPlugins#20]
**Describe the bug**
I'm talking about NitroEmoteAndScreenShareBypass, again. Seems like BD doesn't handle auto-update from sourced link, there's a need for some kind of auto-update function (or maybe I don't understand something). Let me know if it works for you, please.

I'm not good at js, so I can offer help as a tester.

**BD Version**
BetterDiscord 1.5.1

**Additional context**
I have plugin v4.0 installed, noticed new commit and version 4.1, yet there was no prompt in my Discord.

**Comment by oSumAtrIX** [comment]
My only guess would be, that it will prompt to update after some time, maybe there is a specific update cycle. Give it a day or couple hours and let me know if that did it.

**Comment by Corwin616** [comment]
same problem, NitroEmoteAndScreenShareBypass v3.6.3

**Comment by skelly37** [comment]
> My only guess would be, that it will prompt to update after some time, maybe there is a specific update cycle. Give it a day or couple of hours and let me know if that did it.

Nope, still nothing. I receive other updates, tho, so it's not a problem with my BD. My guess is that some handler in the plugin is needed.

**Comment by oSumAtrIX** [comment]
> My guess is that some handler in the plugin is needed.

There is no issue with the metadata of the plugin. It has all necessary fields as described in [the wiki](https://github.com/BetterDiscord/BetterDiscord/wiki/Plugin-and-Theme-METAs#common-fields) to allow auto-updating.

**Comment by skelly37** [comment]
> > My guess is that some handler in the plugin is needed.
> 
> There is no issue with the metadata of the plugin. It has all necessary fields as described in [the wiki](https://github.com/BetterDiscord/BetterDiscord/wiki/Plugin-and-Theme-METAs#common-fields) to allow auto-updating.

Yup, I've just went through them and found the same. Really weird issue, everything seems to be correct.

**Comment by skelly37** [comment]
If no one comes up with a better idea, I sugesst to try making a really hacky thing — manually get the github file on startup, compare it with the local one and if needed (and possible in BetterDiscord) replace the file and restart plugin. 

Maybe it's dirty but imo still more convenient than manual updates.

**Comment by oSumAtrIX** [comment]
In this regard, I would rather try to solve the issue of BetterDiscord and not try to fix around a problem.

**Comment by skelly37** [comment]
I moved the issue to main BetterDiscord then.
