### ISSUE TITLE
Emoji plugin conflict

### ISSUE THREAD

**Issue by AtlanticDragon** [oSumAtrIX/BetterDiscordPlugins#22]
Since I'm only using betterdiscord, and the emoji override is for something else, I have instead gotten a seperate plugin, Freemoji https://betterdiscord.app/plugin/Freemoji  But your code prevents freemoji from working correctly. If you could add an option to disable the emoji overide part and only use the screenshare features it would be awesome. Or if you like, I could comment out the part of your code that does that emoji overide in my own local file version but I'm not sure where/how to do that.

**Comment by skelly37** [comment]
Agreed, the plugins should be split into two imo.

**Comment by oSumAtrIX** [comment]
Freemoji does the same what this plugin does. Why should you want to use Freemoji if you can just use this

**Comment by AtlanticDragon** [comment]
Because freemoji has a workaround that just converts the emojis to a gif link that you post instead of tricking discord into thinking you have nitro.  Basically, when Im just using yours, when I try post an animated emoji, it will display for a millisecond then show up as :bounce: or what ever the name is. And I wanna say this is because Im just using betterdiscord and nothing else. But the 60fps streaming works perfectly.

**Comment by AtlanticDragon** [comment]
will I have to redownload when the fix is made?

**Comment by oSumAtrIX** [comment]
For me, the plugin is working fine, do you have Zeres lib?

**Comment by AtlanticDragon** [comment]
BDFDB v2.2.4? I also had this other one called ZeresPluginLibrary v2.0.2 but I had that disabled

**Comment by AtlanticDragon** [comment]
I just went and reinstalled the library and got rid of freemoji, reloaded discord. It still isnt coverting it to a to a gif. Is there a different place I should be getting techinical help? On the official better discord's server they dont offer help with your specific plugin.

**Comment by oSumAtrIX** [comment]
Here is the right place, I need error logs, collect them while sending a gif emote

**Comment by AtlanticDragon** [comment]
Where do I find the logs to send?

**Comment by AtlanticDragon** [comment]
Okay I cant seem to open the console after pressing ctrl shift I. im not sure why

**Comment by oSumAtrIX** [comment]
Not sure either why, anyways, I would need logs to continue debugging this, after you solve the console issue

**Comment by AtlanticDragon** [comment]
I just now found it, there were more settings to enable the devtools in the Betterdiscord settings. will try to get logs now.

**Comment by AtlanticDragon** [comment]
Hey I just want to first apologise for wasting your time. I just redownloaded the plugin but from [your page](https://github.com/oSumAtrIX/BetterDiscordPlugins), I had initially downloaded [someone else's collection](https://github.com/Calatop/Free-Discord-Nitro) which included your one plugin by itself amongst a few others. I also disabled all my plugins except the library and BDFDB and some how it works now! Not sure what exact part of this process made it work.

**Comment by AtlanticDragon** [comment]
So like now that this works, I can also still use freemoji with it because freemoji has a few more options like you can hide the link if you put the emoji in the middle of your message but that seems to just work seemlessly with your so it's all good all around.
