### ISSUE TITLE
nitrobypass

### ISSUE THREAD

**Issue by speedlorenzo12** [oSumAtrIX/BetterDiscordPlugins#26]
**Describe the bug**
it works very well but some new things like: nitro activity and nitro profile customization doesn't get them done

**To Reproduce**
1. Go to the activity and customization profile
2. Click on 1 activity whit nitro obbligation and customization profile
3. in the activity it ends with a failed instead the nitro profile i cannot use the nitro features

**BD Version**
stable 1.8.2 

**Screenshots/ Videos**
sorry for italian
![Screenshot (29 1)](https://user-images.githubusercontent.com/111771663/198291773-f80df08d-fc61-40ab-8534-3cc553a2d6fe.png)

**Comment by oSumAtrIX** [comment]
The plugin name is `NitroEmoteAndScreenShareBypass`.
