### ISSUE TITLE
Plugins problem

### ISSUE THREAD

**Issue by Chris-AY** [oSumAtrIX/BetterDiscordPlugins#28]
Hello
I have downloaded the file but it didn't work
![image1](https://github.com/oSumAtrIX/BetterDiscordPlugins/assets/173930892/1da74778-5251-4fc7-95bd-d2dd1122ddf8)
![image](https://github.com/oSumAtrIX/BetterDiscordPlugins/assets/173930892/ea151535-9da4-4a7b-9ad6-a7a4584d1bd4)

I can not use nitro emojis

**Comment by oSumAtrIX** [comment]
In the console do you see any errors
