### ISSUE TITLE
Doesn't work on new version of BD

### ISSUE THREAD

**Issue by cheluu-oss** [oSumAtrIX/BetterDiscordPlugins#6]
The emojis are broken

**Comment by cheluu-oss** [comment]
https://user-images.githubusercontent.com/73129251/113388963-d9e5e880-9397-11eb-8fcd-366d45d80997.mp4

**Comment by respecting** [comment]
not trying to self promote but I've kinda rewrote the plugin in zerespluginlibrary and it should work with the new beta
[here's the link if you're interested](https://raw.githubusercontent.com/respecting/NitroPerks/master/NitroPerks.plugin.js)
screensharing is off by default, you can toggle it in settings
